Asm
Nesterfifa/first-term pull request #2
Opened 2020-07-02 19:59 UTC by Nesterfifa

2020-07-03 20:20 UTC, kt-cpp requested changes

2020-07-03 20:20 UTC, kt-cpp commented on asm/mul.asm
> +                add             rsi, 4 * 128 * 8
Хардкод. Все параметры функция должна узнавать из свлих аргументов и по хорошему не полагаться на расположение своих аргументов в памяти

2020-07-03 20:20 UTC, kt-cpp commented on asm/mul.asm
> +                mov             r9, 128
Снова хардкод

2020-07-03 20:20 UTC, kt-cpp commented on asm/mul.asm
> +                mov             [rdi + 128 * 8 * 3], rax
Снова хардкод

2020-07-03 20:20 UTC, kt-cpp commented on asm/mul.asm
> +                mov             rcx, 129
Снова хардкод

2020-07-03 20:20 UTC, kt-cpp commented on asm/mul.asm
> +                lea             rdi, [rdi - 128 * 8 * 2 + r8 * 8]
Снова хардкод

2020-07-03 20:20 UTC, kt-cpp commented on asm/mul.asm
> +                mov             rcx, 129
Снова хардкод

2020-07-03 20:20 UTC, kt-cpp commented on asm/mul.asm
> +                mov             rcx, 129
Снова хардкод

2020-07-03 20:20 UTC, kt-cpp commented on asm/mul.asm
> +.loop_copy:
Вынеси в отдельную функцию с понятным контрактом

2020-07-03 20:20 UTC, kt-cpp commented on asm/mul.asm
> +.loop_copy:
И вместо безымянных сдвигов лучше использовать именованные регистры для адреса буфера

2020-07-04 10:19 UTC, Nesterfifa commented on asm/mul.asm
> +                add             rsi, 4 * 128 * 8
fixed

2020-07-04 10:19 UTC, Nesterfifa commented on asm/mul.asm
> +                mov             r9, 128
fixed

2020-07-04 10:19 UTC, Nesterfifa commented on asm/mul.asm
> +                mov             [rdi + 128 * 8 * 3], rax
fixed

2020-07-04 10:19 UTC, Nesterfifa commented on asm/mul.asm
> +                mov             rcx, 129
fixed

2020-07-04 10:20 UTC, Nesterfifa commented on asm/mul.asm
> +                lea             rdi, [rdi - 128 * 8 * 2 + r8 * 8]
fixed

2020-07-04 10:20 UTC, Nesterfifa commented on asm/mul.asm
> +                mov             rcx, 129
fixed

2020-07-04 10:20 UTC, Nesterfifa commented on asm/mul.asm
> +                mov             rcx, 129
fixed

2020-07-04 10:20 UTC, Nesterfifa commented on asm/mul.asm
> +.loop_copy:
fixed

2020-07-06 12:01 UTC, kt-cpp commented on asm/mul.asm
> +                mov             rcx, LEN * 2
indent

2020-07-06 12:02 UTC, kt-cpp commented on asm/mul.asm
> +                sub             rsp, 6 * LEN * 8
Здесь кусок памяти под temp вычисления не нужен, выдели его в соответствующей функции

2020-07-06 12:03 UTC, kt-cpp commented on asm/mul.asm
> +                sub             rsp, 6 * LEN * 8
И там будет видно что тебе достаточно `(LEN + 1) * 8`

2020-07-06 12:03 UTC, kt-cpp requested changes
Почти ок

2020-07-07 08:40 UTC, Nesterfifa commented on asm/mul.asm
> +                mov             rcx, LEN * 2
fixed

2020-07-07 08:40 UTC, Nesterfifa commented on asm/mul.asm
> +                sub             rsp, 6 * LEN * 8
fixed

2023-06-12 08:59 UTC, merged