finally I have bigint
Nesterfifa/first-term pull request #4
Opened 2020-10-01 23:16 UTC by Nesterfifa

2020-10-02 22:33 UTC, kt-cpp requested changes

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.h
> +std::ostream& operator<<(std::ostream& s, big_integer const& a);
[minor] Перенос в конце файла

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    digits[0] = (a == INT_MIN ? static_cast<uint32_t>(INT_MAX) + 1 : abs(a));
[minor] А может вместо каста более понятный `std::numeric_limits<uint32_t>::max()`

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    sign = (str[0] == '-' && digits.back() != 0);
* Нет проверки корректности ввода
* `substr` делает копию, а зачем?

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer::~big_integer() = default;
[minor] Если такое хочется писать, то стоит это сделать в хедере

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        carry = res > UINT32_MAX;
Вместо условных операций можно просто желать безусловный сдвиг

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
Тут происходит много лишних копирований, которые можно избежать, если правильно разобрать случаи

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        return *this = -(rhs - *this);
Тут происходит много лишних копирований, которые можно избежать, если правильно разобрать случаи

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        uint64_t const res = static_cast<uint64_t>(digits[i]) + (i < rhs.size() ? rhs.digits[i] : 0) + carry;
[minor] `(i < rhs.size() ? rhs.digits[i] : 0)` Вижу не один раз такую конструкцию. Мб вынести её в функцию?

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
Мб просто аккуратно вычитать из двух разрядов вычитаемого один разряд уменьшаемого, чтобы не ввязываться в операции между знаковыми и беззнаковыми одновременно?

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +                    + ans.digits[i + j];
Будет неловко, если `carry` и `ans.digits[i + j]` сложатся первыми как `uint32_t` и результат молча переполнится

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        for (size_t j = 0; j < rhs.size() || carry; j++) {
Зачем условие на `carry`, ибо из-за порядка обхода его можно безусловно вставлять всегда в конце?

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    big_integer ans(a);
А зачем тут копировать `a`, а не просто заполнять нулями?

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        uint64_t dividend = static_cast<uint64_t>(ans.digits[i]) + rem * (static_cast<uint64_t>(1) << 32u);
Почему бы не сделать `rem` 64битным и просто каждый раз его двигать влево?

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    bool carry = false;
Аналогичное замечание как с `borrow` в `-=`

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        return *this = big_integer();
[minor] Но ведь `ans` уже есть дефолтный бигинт...

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            }
Кажется в общем случае результат может отличать больше чем на 1 от истинного, хоть вероятность этого крайне мала

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        for (size_t i = 0; i <= n - m; i++) {
А где нормализация? Без неё деление работает медленнее (`trial` чаще ошибается)

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    big_integer this_copy(*this), rhs_copy(rhs);
* [note] При сильном желании можно не копировать, а завести геттер со стейтом
* [minor] Две переменные на одной строке

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return -*this - 1;
Можно делать меньше копирований

2020-10-02 22:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
[note] Можно делать быстрее, если делить не на 10, а  на 1'000'000'000

2020-10-03 11:37 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +    digits[0] = (a == INT_MIN ? static_cast<uint32_t>(INT_MAX) + 1 : abs(a));
Я тут делаю каст в беззнаковый максимума в знаковом int и прибавляю единицу, мне не максимальный uint32_t нужен

2020-10-04 22:55 UTC, Nesterfifa commented on bigint/big_integer.h
> +std::ostream& operator<<(std::ostream& s, big_integer const& a);
fixed

2020-10-04 22:55 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +    sign = (str[0] == '-' && digits.back() != 0);
fixed

2020-10-04 22:55 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +big_integer::~big_integer() = default;
fixed

2020-10-04 22:55 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +        carry = res > UINT32_MAX;
fixed

2020-10-04 22:56 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +    }
Полностью переписал, кода больше, но кажется копирований сильно меньше

2020-10-04 22:56 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +        return *this = -(rhs - *this);
Полностью переписал, кода больше, но кажется копирований сильно меньше

2020-10-04 22:56 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +        uint64_t const res = static_cast<uint64_t>(digits[i]) + (i < rhs.size() ? rhs.digits[i] : 0) + carry;
fixed

2020-10-04 22:57 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +    }
В переписанном вычитании в одном из случаев вычитаем из rhs, поэтому вычитание не из двух разрядов, но без знаковых операций

2020-10-04 22:57 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +                    + ans.digits[i + j];
fixed

2020-10-04 22:58 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +        for (size_t j = 0; j < rhs.size() || carry; j++) {
fixed

2020-10-04 22:58 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +    big_integer ans(a);
fixed

2020-10-04 22:58 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +        uint64_t dividend = static_cast<uint64_t>(ans.digits[i]) + rem * (static_cast<uint64_t>(1) << 32u);
fixed

2020-10-04 22:59 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +    bool carry = false;
Тут написал вычитание из 2 + (количество разрядов-нулей) разрядов уменьшаемого

2020-10-04 22:59 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +        return *this = big_integer();
fixed

2020-10-04 22:59 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +            }
fixed

2020-10-04 23:00 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +    big_integer this_copy(*this), rhs_copy(rhs);
minor fixed

2020-10-04 23:00 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +    return -*this - 1;
fixed

2020-10-04 23:03 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +        for (size_t i = 0; i <= n - m; i++) {
fixed

2020-10-05 11:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    sign = (str[0] == '-' && digits.back() != 0);
"-12😏😡💦❤️" выглядит как валидное число для тебя

2020-10-05 11:52 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        carry = res > UINT32_MAX;
Я скорее предлагал использовать 64битный `carry`, ибо каст инегрального типа к логическому мало чем отличается от условного оператора

2020-10-05 11:57 UTC, kt-cpp commented on bigint/big_integer.cpp
> +                    + ans.digits[i + j];
Почему бы просто не сделать 64битный carry?

2020-10-05 12:01 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    bool carry = false;
Вышло совсем не то, что я имел в виду. Должна получить ситуация аналогичная вычитанию, где ты на каждой итерации делишь `k + 1` на `k` значное. Только тут вычитаешь из 64битного 32битное

2020-10-05 13:47 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
Казалось бы ты всё ещё можешь делать, что я описал причём это даже будет выглядеть довольно аккуратно, ибо тебе `i + 1` элемент вектора первый раз нужен только на чтение, а `i` после чтения можно смело писать, как ты и делаешь сейчас

2020-10-05 13:48 UTC, kt-cpp requested changes
Отписал в старые треды

2020-10-07 15:33 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +    sign = (str[0] == '-' && digits.back() != 0);
fixed, теперь проверяется не через 8

2020-10-07 15:33 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +        carry = res > UINT32_MAX;
fixed

2020-10-07 15:33 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +    }
Не совсем без borrow_magic, ибо без нее падает на 100|00..0|00..01 - 111|11..11|11..1000, но кажется выглядит как то что описывалось

2020-10-07 15:33 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +                    + ans.digits[i + j];
fixed

2020-10-07 15:33 UTC, Nesterfifa commented on bigint/big_integer.cpp
> +    bool carry = false;
same as in `-=`

2020-10-09 07:51 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
Там проблема с займом через несколько разрядов, ты прав

2020-10-09 07:51 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    bool carry = false;
Там проблема с займом через несколько разрядов, ты прав

2020-10-09 07:52 UTC, kt-cpp approved these changes

2020-10-09 07:52 UTC, merged