Bigint opt
Nesterfifa/first-term pull request #5
Opened 2020-10-12 10:30 UTC by Nesterfifa

2020-10-13 08:50 UTC, kt-cpp requested changes
Довольно неплохо, но всё же есть косяки

2020-10-13 08:50 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +    typedef uint32_t const* const_iterator;
`using`

2020-10-13 08:50 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +    }
Это можно сделать за <=1 одну аллокацию

2020-10-13 08:50 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +            != (other.small() ? other.static_data[i] : other.dynamic_data->data[i])) {
Так называемый `operator[]`?

2020-10-13 08:50 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +    static constexpr size_t FLAG = static_cast<size_t>(1) << 31u;
Почему 31 разряд, а не 63? Если ты хочешь сделать код работающим на любой системе, то надо отталкиваться от размера на `size_t` на ней, а не ограничивать всё 32битными

2020-10-13 08:50 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +            size_ |= FLAG;
Это действие надо производить строго после того, как ты успешно выделил данные на куче и присвоил их в твой вектор. Иначе при вылете исключения в `allocate_buffer` деструктор вектора подумает что он сейчас хранит данные на хипе и произойдёт что-то странное

2020-10-13 08:50 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +    }
* Условия на 82 строчке не достаточно, ибо у тебя мог быть вектор, с данными на куче, у которого просто много раз вызывали `pop_back`
* Сейчас в момент перехода из small в big происходит 2 аллокации и хочется это исправить:
  * Для перевода данных их статического массива на кучу
  * Увеличение динамического буффера в 2 раза ибо `size() == capacity()`
* Так же происходит две аллокации в случае, если динамический буффер находится в раздельно владении И при этом `size() == capacity()`

2020-10-13 08:50 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +            std::copy_n(this_data, sz, other.static_data);
* У тебя ситуации, когда `this->small() && !other.small()`, и `!(this->small()) && other.small()` почему это отличаются по количеству дополнительных копирования, хотя не должны. Мб вынести в отдельную функцию и переиспользовать?
* Вместо копии статического буфера, если оба мелкие, можно просто вызвать специализацию swap для массивов. Так у тебя они содержат примитивные типы, то своп элементов за границами реального размера ничего не сломает

2020-10-13 08:50 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +    }
Кажется надо реализовывать эту функцию руками, а уже через неё `iterator insert(const_iterator it, uint32_t const& elem)`, иначе ты рискуешь получить квадратичную сложность

2020-10-13 08:50 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +            }
А кто сделает `unshare` перед изменением элементов в буфере?

2020-10-13 08:50 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +            }
Если ты так заботишься о лишних `if``, то почему тут просто не уменьшить размер за одну инструкцию и всё?

2020-10-13 16:28 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +    }
1) У меня при переходе в big я делаю `size_ |= FLAG`, если потом поп-бекнуть `size()` раз, то будет `size_ == FLAG` и это явно больше чем `MAX_SMALL`.
2) Теперь `to_big` умеет в кастомную `capacity` и может аллоцировать сразу `2 * capacity()` если надо
3) Теперь `unshare` умеет в кастомную `capacity` и может аллоцировать сразу `2 * capacity()` если надо

2020-10-13 18:08 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +            std::copy_n(this_data, sz, other.static_data);
fixed

2020-10-13 18:09 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +            size_ |= FLAG;
fixed

2020-10-13 18:09 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +    static constexpr size_t FLAG = static_cast<size_t>(1) << 31u;
fixed

2020-10-13 18:09 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +            != (other.small() ? other.static_data[i] : other.dynamic_data->data[i])) {
fixed

2020-10-13 18:09 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +    }
fixed

2020-10-13 18:09 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +    typedef uint32_t const* const_iterator;
fixed

2020-10-13 18:10 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +    }
fixed

2020-10-13 18:11 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +            }
fixed

2020-10-13 18:11 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +            }
fixed

2020-10-13 20:24 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +    }
По поводу 1, лучше не полагаться на такие фокусы, а честно проверить что `small() && size() < MAX_SMALL`

2020-10-13 20:25 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +            != (other.small() ? other.static_data[i] : other.dynamic_data->data[i])) {
Почему не `(*this)[i] != other[i]`?

2020-10-13 20:29 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +    }
* Куда делись вполне уместные свапы?
* Снова замечание про вызов `operator[]`

2020-10-13 20:35 UTC, kt-cpp requested changes
Почти готово, плюс прочти старые треды

2020-10-13 20:35 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +            }
`std::fill` или `std::fill_n`

2020-10-13 20:35 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +            }
`std::fill` или `std::fill_n`

2020-10-13 20:35 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
>              if (size() == capacity()) {
Кажется весь этот иф теперь не нужен

2020-10-13 20:35 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
>          }
Почему бы сразу не вставлять `elem`?

2020-10-13 20:35 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +                std::swap(operator[](i), operator[](i + len));
Снова вызов оператора

2020-10-13 20:35 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +    static constexpr size_t FLAG = static_cast<size_t>(1) << (8 * sizeof(size_t) - 1);
Если уже совсем идти по пути портируемости, то `8`  тоже [не выбито в камне](http://www.cplusplus.com/reference/climits/)

2020-10-13 20:35 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +    void unshare(size_t capacity) {
Сюда бы ассёрт, что новая вместимость не меньше старого размера

2020-10-13 20:35 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +    void to_big(size_t capacity) {
Сюда бы ассёрт, что новая вместимость не меньше старого размера

2020-10-13 20:35 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +    static void swap(optimized_vector &a, optimized_vector& b) {
Лучше это условие так же отразить в имени функции и переменных

2020-10-13 21:08 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
>              if (size() == capacity()) {
Нужен, потому что если мы уже big и при этом мы единственные кто ссылается на наши данные, то `to_big` и `unshare` не сделают ничего, а `size() == capacity()` вполне может произойти

2020-10-13 21:11 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +            != (other.small() ? other.static_data[i] : other.dynamic_data->data[i])) {
fixed

2020-10-13 21:11 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +    }
fixed

2020-10-13 21:11 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +    }
fixed

2020-10-13 21:11 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +            }
fixed

2020-10-13 21:11 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +            }
fixed

2020-10-13 21:12 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
>          }
fixed

2020-10-13 21:12 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +                std::swap(operator[](i), operator[](i + len));
fixed

2020-10-13 21:13 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +    void unshare(size_t capacity) {
fixed

2020-10-13 21:13 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +    void to_big(size_t capacity) {
fixed

2020-10-13 21:13 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +    static void swap(optimized_vector &a, optimized_vector& b) {
fixed

2020-10-13 21:15 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +    static constexpr size_t FLAG = static_cast<size_t>(1) << (8 * sizeof(size_t) - 1);
fixed

2020-10-14 20:57 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +    void unshare(size_t capacity) {
Размера, а не вместимости. Тебе уменьшенение вместимости ничего не ломает. А вот если `size() < new_capacity`, то код ниже сломается

2020-10-14 20:57 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +    void to_big(size_t capacity) {
Размера, а не вместимости. Тебе уменьшенение вместимости ничего не ломает. А вот если `size() < new_capacity`, то код ниже сломается

2020-10-14 21:08 UTC, kt-cpp requested changes
Плюс ответил в старые треды

2020-10-14 21:08 UTC, kt-cpp commented on bigint-optimized/optimized_vector.h
> +        std::swap(small_vector.size_, big_vector.size_);
Лучше заводить временную копию `dynamic_data`, ибо это всего лишь один указатель, который копируется за буквально одну инструкцию

2020-10-14 22:00 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +        std::swap(small_vector.size_, big_vector.size_);
fixed

2020-10-14 22:00 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +    void to_big(size_t capacity) {
fixed

2020-10-14 22:00 UTC, Nesterfifa commented on bigint-optimized/optimized_vector.h
> +    void unshare(size_t capacity) {
fixed

2020-10-14 22:15 UTC, kt-cpp approved these changes

2020-10-14 22:16 UTC, merged